server {
    listen          80;
    server_name     _;
    
    access_log  /var/log/nginx/edgenext-website-static.access.log  main;
    error_log  /var/log/nginx/edgenext-website-static.error.log  error;

    location /blogphoto/ {
        root        /usr/share/nginx/html;
        try_files   $uri =404;
    }

    location / {
        root        /usr/share/nginx/html;
        index       index.html index.htm;
        try_files   $uri $uri.html $uri/ /index.html;
    }
}